/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.Menus;

/**
 *
 * @author isabelgutierrez
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresarC = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnGrafoAdmi = new javax.swing.JButton();
        btnArbolAdmi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnConsultaParticipantesAdmi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas");

        btnRegresarC.setForeground(new java.awt.Color(0, 255, 51));
        btnRegresarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/atras.png"))); // NOI18N
        btnRegresarC.setText("Regresar");
        btnRegresarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarCActionPerformed(evt);
            }
        });

        btnSalir1.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/salida.png"))); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnGrafoAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/002-equipo.png"))); // NOI18N
        btnGrafoAdmi.setText("Grafo de Equipos");
        btnGrafoAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoAdmiActionPerformed(evt);
            }
        });

        btnArbolAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/001-juego-de-azar.png"))); // NOI18N
        btnArbolAdmi.setText("Árbol de Clasificación");
        btnArbolAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolAdmiActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/018-pelotas.png"))); // NOI18N
        jLabel2.setText("     Seleccione la opción que desea realizar");

        btnConsultaParticipantesAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/005-tarjeta-de-identificacion.png"))); // NOI18N
        btnConsultaParticipantesAdmi.setText("Consulta de Participantes");
        btnConsultaParticipantesAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaParticipantesAdmiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnConsultaParticipantesAdmi, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGrafoAdmi)
                .addGap(18, 18, 18)
                .addComponent(btnArbolAdmi)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(btnSalir1)
                        .addGap(136, 136, 136)
                        .addComponent(btnRegresarC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArbolAdmi)
                    .addComponent(btnGrafoAdmi)
                    .addComponent(btnConsultaParticipantesAdmi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarC)
                    .addComponent(btnSalir1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarCActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarCActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnGrafoAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrafoAdmiActionPerformed

    private void btnArbolAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArbolAdmiActionPerformed

    private void btnConsultaParticipantesAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaParticipantesAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaParticipantesAdmiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbolAdmi;
    private javax.swing.JButton btnConsultaParticipantesAdmi;
    private javax.swing.JButton btnGrafoAdmi;
    private javax.swing.JButton btnRegresarC;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
