/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal.Menus;

/**
 *
 * @author isabelgutierrez
 */
public class GestionParticipantes extends javax.swing.JFrame {

    /**
     * Creates new form GestionParticipantes
     */
    public GestionParticipantes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegresarGP = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnActualizarParticipantes = new javax.swing.JButton();
        btnEliminarParticipantes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRegistrarParticipantes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Participantes");

        btnRegresarGP.setForeground(new java.awt.Color(0, 255, 51));
        btnRegresarGP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/atras.png"))); // NOI18N
        btnRegresarGP.setText("Regresar");
        btnRegresarGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarGPActionPerformed(evt);
            }
        });

        btnSalir1.setForeground(new java.awt.Color(255, 0, 0));
        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/salida.png"))); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnActualizarParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/011-editar.png"))); // NOI18N
        btnActualizarParticipantes.setText("Actualizar Participantes");
        btnActualizarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarParticipantesActionPerformed(evt);
            }
        });

        btnEliminarParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/010-eliminar.png"))); // NOI18N
        btnEliminarParticipantes.setText("Eliminar Participantes");
        btnEliminarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarParticipantesActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/018-pelotas.png"))); // NOI18N
        jLabel2.setText("     Seleccione la opción que desea realizar");

        btnRegistrarParticipantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/png/012-agregar.png"))); // NOI18N
        btnRegistrarParticipantes.setText("Registrar Participantes");
        btnRegistrarParticipantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarParticipantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarParticipantes, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarParticipantes)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarParticipantes)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnSalir1)
                        .addGap(119, 119, 119)
                        .addComponent(btnRegresarGP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarParticipantes)
                    .addComponent(btnActualizarParticipantes)
                    .addComponent(btnRegistrarParticipantes))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir1)
                    .addComponent(btnRegresarGP))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarGPActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarGPActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnActualizarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarParticipantesActionPerformed

    private void btnEliminarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarParticipantesActionPerformed

    private void btnRegistrarParticipantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarParticipantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarParticipantesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionParticipantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarParticipantes;
    private javax.swing.JButton btnEliminarParticipantes;
    private javax.swing.JButton btnRegistrarParticipantes;
    private javax.swing.JButton btnRegresarGP;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
